spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/freedesk_desk_service
    username: springstudent
    password: springstudent
  application:
    name: reservation-service
server:
  port: 8083


client:
  feign:
    user-service:
      path: http://localhost:8081/user
      extractUserIdByEmail: /get/userId

    token-service:
      path: http://localhost:8079/token-service
      extractEmail: /token/extract/email
      extractUserId: /token/extract/userId